name: Build & Release

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.22.1

      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev

      - run: flutter pub get
      - run: flutter build linux --release

      - uses: actions/upload-artifact@v4
        with:
          name: linux-release
          path: build/linux/x64/release/bundle/

  build-windows:
    name: Build Windows
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.22.1

      - run: flutter pub get
      - run: flutter build windows --release

      - uses: actions/upload-artifact@v4
        with:
          name: windows-release
          path: build/windows/x64/runner/Release/

  build-macos:
    name: Build macOS
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.22.1

      - run: flutter pub get
      - run: flutter build macos --release

      - uses: actions/upload-artifact@v4
        with:
          name: macos-release
          path: build/macos/Build/Products/Release/

  build-apk:
    name: Build Android APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.22.1

      - run: flutter pub get
      - run: flutter build apk --release

      - uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-release.apk

  build-ios:
    name: Build iOS (.app)
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.22.1

      - run: flutter pub get
      - run: flutter build ios --release --no-codesign

      - uses: actions/upload-artifact@v4
        with:
          name: ios-app
          path: build/ios/iphoneos/Runner.app

  release:
    name: Upload GitHub Release
    needs:
      - build-linux
      - build-windows
      - build-macos
      - build-apk
      - build-ios
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Show artifact structure (debug)
        run: ls -R artifacts

      - name: Prepare release files
        run: |
          cd artifacts
          zip -r ../irene-linux.zip linux-release
          zip -r ../irene-windows.zip windows-release
          zip -r ../irene-macos.zip macos-release

          if [ -f android-apk/app-release.apk ]; then
            mv android-apk/app-release.apk ../irene-android.apk
          else
            echo "APK not found!" && exit 1
          fi

          if [ -d ios-app ]; then
            mv ios-app ../irene-ios.app
          else
            echo "ios-app not found!" && exit 1
          fi

      - name: Upload Release to GitHub
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            irene-linux.zip
            irene-windows.zip
            irene-macos.zip
            irene-android.apk
            irene-ios.app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
